### ISSUE TITLE
M1电脑 安装完后用你项目自带的key,解析失败

### ISSUE THREAD

**Issue by xiaogehenjimo** [JerryFans/mars_xlog_decoder_gui#1]

**Comment by xiaogehenjimo** [comment]
操作步骤:
1.iOS程序中使用您那个demo生成log日志
2.使用您打包好的dmg安装到M1电脑中
3.进行解压log日志, 提示Xlog解析失败,请检查您的private key是否正确

**Comment by jeateediao** [comment]
同遇到，Apple M1 Pro，MacOS Monterey

**Comment by jeateediao** [comment]
> 操作步骤: 1.iOS程序中使用您那个demo生成log日志 2.使用您打包好的dmg安装到M1电脑中 3.进行解压log日志, 提示Xlog解析失败,请检查您的private key是否正确

同遇到，Apple M1 Pro，MacOS Monterey

**Comment by JerryFans** [comment]
建议手工编译一次项目 用debug 版本 看是否可行。 大概率是一些权限问题。 可惜我手头目前没有m1的机子

**Comment by JerryFans** [comment]
v1.2 release已经支持m1系列 macOS 设备。可用直接下载releases安装包使用 。

**Comment by xiaogehenjimo** [comment]
> v1.2 release已经支持m1系列 macOS 设备。可用直接下载releases安装包使用 。

太赞了,感谢作者

**Comment by MustangYM** [comment]
M1 MAX 设备依然弹窗"Xlog解析失败,  请检查你的pricate_key是否正确"
系统:13.2.1

**Comment by JerryFans** [comment]
您使用的是1.2 release的版本吗？
