### ISSUE TITLE
Apple M1 pro，MacOS Monterey 点击生成RSA Key弹窗，点击复制内容为空，在Intel机器上是OK的，看起来M1需要适配

### ISSUE THREAD

**Issue by jeateediao** [JerryFans/mars_xlog_decoder_gui#2]

**Comment by JerryFans** [comment]
感谢提issue 我尽量看有没有 m1的机器调试下。 我自己还是用的2019 macbook pro

**Comment by JerryFans** [comment]
v1.2 release已经支持m1系列 macOS 设备。可用直接下载releases安装包使用 。

**Comment by jeateediao** [comment]
> v1.2 release已经支持m1系列 macOS 设备。可用直接下载releases安装包使用 。

TQL
