### ISSUE TITLE
更新内置解码程序

### ISSUE THREAD

**Issue by suyulin** [JerryFans/mars_xlog_decoder_gui#3]
hi, 
我会提一个pr, 使用 https://github.com/0x1306a94/tencent-mars-xlog-rust的可执行文件 替换python 解密，是否会通过？以下是性能对比
![image](https://user-images.githubusercontent.com/6275411/234453876-7ecb6046-d0cc-47d5-afa3-41915e2e5d37.png)

**Comment by JerryFans** [comment]
欢迎pr 其实c速度是不是更快呢。

**Comment by JerryFans** [comment]
可以的 ，欢迎PR 但是要注意 intel 和 m1 的兼容， 后期考虑兼容windows。 其他没啥了。 没两种机子的话 你提pr 我还是会验证一下的。

**Comment by suyulin** [comment]
> 欢迎pr 其实c速度是不是更快呢。
我也不会写C啊,rust已经很够用了。
 原本使用chatgpt 把python 代码翻译成 rust,有人实现就不必重复早轮子了。
pr mac 和 win 都支持，这个礼拜这内提。
