### ISSUE TITLE
未加密的xlog文件无法解密成功

### ISSUE THREAD

**Issue by hahaha28** [JerryFans/mars_xlog_decoder_gui#5]
大佬，未加密的xlog文件无法解密成功，加密的可以

**Comment by JerryFans** [comment]
看了下前几天改动的代码 确实未加密的解析 命令是不对的 麻烦您发一个未加密xlog我测试下 我好修复？

**Comment by hahaha28** [comment]
[_20230517.xlog.zip](https://github.com/JerryFans/mars_xlog_decoder_gui/files/11493846/_20230517.xlog.zip)
辛苦大佬看看

**Comment by JerryFans** [comment]
已修复 稍后我会release一个安装包， 如果你想验证 你可以拉最新代码，然后自己flutter run -d macos一下。 现在的环境是flutter 3.7.9

**Comment by hahaha28** [comment]
感谢大佬😘
